### ISSUE TITLE
[21-06-10]: [Cierre inesperado de aplicación]

### ISSUE THREAD

**Issue by isaiep** [RamiroEda/SAES-para-Alumnos#22]
- [X ] Al marcar esta casilla entiendo que "SAES para Alumnos" NO es un producto oficial del Instituto Politécnico Nacional (IPN) ni ninguna de sus unidades académicas.
- [X] Al marcar esta casilla aseguro que he revisado la lista de Issues por si alguien ya creó un problema igual al mío o ya ha sido solucionado.

Prácticamente la aplicación se cierra al ingresar mis e iniciar sesión.
## Comportamiento esperado
La aplicación debería arrojar la pantalla principal de la aplicación en donde se muestra el resumen de calificaciones y noticias.

## Comportamiento actual
La aplicación se cierra en cuanto trato de iniciar sesión.

## Pasos para reproducir

1.Ingresen mis datos en el apartado medio superior
2.seleccionen CECyT 1. Y pongan 2019010083 en boleta y en contraseña ______
3.la aplicación les debe cerrar inesperadamente
4.

**Comment by RamiroEda** [comment]
Gracias por abrir el issue. Este error se debe a un NullPointerException causado por la librería https://github.com/twitter-archive/twitter-kit-android
Tengo la teoría de que tiene que ver con una incompatibilidad de la librería con videos de algún Tweet. La librería ya no está siendo mantenida y puede tener problemas aunque sea oficial.
Revisaré como solucionar el problema asap.

**Comment by RamiroEda** [comment]
Voy a quitar tu contraseña del issue

**Comment by isaiep** [comment]
Está bien, gracias.
________________________________
