### ISSUE TITLE
01/09/2021:Error

### ISSUE THREAD

**Issue by lram-dev** [RamiroEda/SAES-para-Alumnos#26]
No sé visualiza mi horario pero si se ven las materias inscritas 
![Screenshot_20210901-174544_SAES para Alumnos](https://user-images.githubusercontent.com/89947548/131755180-75644e82-96b4-4068-a5b3-daffcdf13da1.jpg)
![Screenshot_20210901-174552_SAES para Alumnos](https://user-images.githubusercontent.com/89947548/131755184-b963b593-dc2c-4a33-8743-335e7d47d756.jpg)

**Comment by RamiroEda** [comment]
Hola, para encontrar el problema lo más pronto posible y no tener que estar preguntandote tantas cosas necesito que me pases el HTML de tu horario, esto se hace de la siguiente manera:

1. Inicia sesión en tu SAES desde cualquier navegador o dispositivo.
2. Entra a la página del horario.
3. Guarda la página cómo se indica [en esta página](https://support.google.com/chrome/answer/7343019?hl=es-419&co=GENIE.Platform%3DDesktop).

Esa página no me dará acceso a ninguna información personal ni me dejará iniciar sesión a tu cuenta, es como una captura de pantalla en la cual puedo ver las propiedades.

**Comment by lram-dev** [comment]
Oye te respondi por aca.
Otra pregunta si quisiera hacer una app como esta para proyecto de
titulación me ayudarían ? Sé que es una app de código abierto pero voy en
6to me falta mucho que entender.

**Comment by RamiroEda** [comment]
Lamentablemente no, estoy en proceso de Trabajo Terminal y realmente no tengo tanto tiempo.

**Comment by lram-dev** [comment]
Bueno muchas gracias espero mi reporte pueda resolver el problema de la app
salu2

**Comment by RamiroEda** [comment]
Bueno, no se si me enviaste el archivo por correo pero no me lo reenvió Github. Podrías enviarlo directamente en la página web?

**Comment by lram-dev** [comment]
Te lo mandé por acá Enviado desde mi Galaxy
-------- Mensaje original --------De: Ramiro Estrada Garcia ***@***.***> Fecha: 1/9/2021  7:10 p. m.  (GMT-06:00) A: RamiroEstradaG/SAES-para-Alumnos ***@***.***> CC: Richscrat ***@***.***>, Author ***@***.***> Asunto: Re: [RamiroEstradaG/SAES-para-Alumnos] 01/09/2021:Error (#26) 

Bueno, no se si me enviaste el archivo por correo pero no me lo reenvió Github. Podrías enviarlo directamente en la página web?

**Comment by RamiroEda** [comment]
Hmmm, no se manda. Si puedes mandarmelo por correo a ramiroestradag@gmail.com

**Comment by lram-dev** [comment]
Listo Enviado desde mi Galaxy
-------- Mensaje original --------De: Ramiro Estrada Garcia ***@***.***> Fecha: 1/9/2021  7:44 p. m.  (GMT-06:00) A: RamiroEstradaG/SAES-para-Alumnos ***@***.***> CC: Richscrat ***@***.***>, Author ***@***.***> Asunto: Re: [RamiroEstradaG/SAES-para-Alumnos] 01/09/2021:Error (#26) 
Hmmm, no se manda. Si puedes mandarmelo por correo a ***@***.***

**Comment by lram-dev** [comment]
Avísame si ya te llegó por favor 🙏

**Comment by RamiroEda** [comment]
Solucionado en 221206422dcbac93075adb153f9d9931c6c5a2f0

**Comment by lram-dev** [comment]
Se actualizará la app o como funciona ?

**Comment by RamiroEda** [comment]
Si, una vez que la Play Store me apruebe la actualización se distribuirá a todos los usuarios. Asegurate mañana de tener la versión 2.0.0-hotfix.4

**Comment by lram-dev** [comment]
Perfecto estaré al pendiente si ocupas algo más con gusto apoyo salu2.
