### ISSUE TITLE
2021-09-06: Error en Widgets

### ISSUE THREAD

**Issue by lram-dev** [RamiroEda/SAES-para-Alumnos#31]
Los Widgets de horario están mal acomodadas las horas
![Screenshot_20210906-200038_Smart Launcher](https://user-images.githubusercontent.com/89947548/132269287-1d024fc4-0cbe-455e-a02b-8adfee6a2303.jpg)
![Screenshot_20210906-200030_Smart Launcher](https://user-images.githubusercontent.com/89947548/132269294-65beaad0-0b79-42e1-9409-094baf6becab.jpg)
Y en algunas clases me duplica la materia pero sin profesor asignado y en la otra si

**Comment by RamiroEda** [comment]
Para el primer caso del horario diario si hay un bug. 

En el segundo caso del horario semanal es una limitación de la API de Widgets en Android el cual no me permite acceder a los objetos directamente. Esto resulta en no poder obtener la altura exacta en píxeles y no poder realizar cálculos. Para solucionar eso ve a la configuración de la app y hay un apartado para calibrar ese widget.

**Comment by RamiroEda** [comment]
Se ha arreglado el problema de la duplicidad de horarios en c496fadc9f5888c23e1c760da9ea376b86459b3e
