### ISSUE TITLE
[FECHA EN 22-01-06]: [Botón para escribir reseña]

### ISSUE THREAD

**Issue by Osares10** [RamiroEda/SAES-para-Alumnos#33]
- [X] Al marcar esta casilla entiendo que "SAES para Alumnos" NO es un producto oficial del Instituto Politécnico Nacional (IPN) ni ninguna de sus unidades académicas.
- [X] Al marcar esta casilla aseguro que he revisado la lista de Issues por si alguien ya creó un problema igual al mío o ya ha sido solucionado.

No redirecciona a la Play Store para escribir reseña.
## Comportamiento esperado

Enviarme a la Playa Store, de preferencia abrir el menú ahora que califique la aplicación y escriba una reseña de la aplicación.
## Comportamiento actual

No pasó nada, no mensaje de error, ninguna respuesta.
## Solucion posible

No he checado el código, pero recomendaría checar las acciones ligadas a dicho botón.
## Pasos para reproducir

1. Abrir la aplicación.
2. Iniciar sesión.
3. Abrir menú, y dirigirse a "Acerca de la aplicación".
4. Presionar el botón "Escribir una reseña".

**Comment by RamiroEda** [comment]
No se puede saber si el usuario ya ha hecho un review por limitaciones de la API entonces cuando ya se hizo review no pasa nada.[(Referencia)](https://developer.android.com/guide/playcore/in-app-review/kotlin-java#launch-review-flow)
