### ISSUE TITLE
14/02/22.  No carga horario 

### ISSUE THREAD

**Issue by IsaacHdz02** [RamiroEda/SAES-para-Alumnos#35]
- [x ] Al marcar esta casilla entiendo que "SAES para Alumnos" NO es un producto oficial del Instituto Politécnico Nacional (IPN) ni ninguna de sus unidades académicas.
- [x ] Al marcar esta casilla aseguro que he revisado la lista de Issues por si alguien ya creó un problema igual al mío o ya ha sido solucionado.

No carga mi horario, solo se queda cargando y surge la leyenda que ha ocurrido un error al actualizar el horario
## Comportamiento esperado

Cargar mi horario para ver mis materias
## Comportamiento actual

No carga, llevo ya 2 semanas así 
## Pasos para reproducir

1.
2.
3.
4.

**Comment by RamiroEda** [comment]
Duplicado #34
